name: flask-app-action

on:
  push:
    tags:
      - "*-run-test"  # Запуск на теги, що закінчуються на '-run-test'




jobs:
  test:
    runs-on: ubuntu-latest  # Використовуємо останню версію Ubuntu

    strategy:
      matrix:
        python-version: ["3.9"]  # Python версія

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Завантаження коду з репозиторію

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}  # Використовуємо Python з матриці

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Встановлення залежностей з requirements.txt

    - name: Run tests
      run: |
        python -m pytest tests/*  # Запуск тестів у папці test/
